spring:
  rabbitmq:
    host: 192.168.17.128
    username: admin
    password: 123
    port: 5672
#    开启发布确认回调
    publisher-confirm-type: correlated
#    发布确认回退
    publisher-returns: true
server:
  port: 8888
